# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 108ec4cb3f8c3bd489727c4584e16d2c5f93d48d26ceb425fd689f37f4b388867887b93662db58ab62a3c75a394f8f7191d2b36877c3c323aabdd8066b7f0faa

test:
  secret_key_base: 72e87a4ffd5407a7fcd9e44852110db9f03fa096ab66bc53d06a99764c48590d062bdfc255db04ff236874cbf67d99717d636836b839d6247527dccf109097b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
